### PR TITLE
[fix] Improve builder to include adding list of metrics

### PR DESCRIPTION
**Pull request by varshaprasad96**
PROBLEM:
Currently, the user has to use WithCollector() function repeatedly
to register each metric. This makes registering of large number
of metrics difficult.

SOLUTION:
This PR provides an additional WithCollectors() function which
takes in a list of metrics which are to be registered with
prometheus. The user, can hence directly provide a list of collectors
to register.

### CODE REVIEW

**Comment by varshaprasad96** [comment]
@awgreene @fahlmant @rafael-azevedo - Please review this PR. I have included the `WithCollectors()` function to register multiple metrics. Also, I have cleaned up the code and removed `WithMetricsFunction` as it seems to be redundant and updated README accordingly.

**Review by fahlmant — APPROVED** [review]
This will make using `WithCollector()` and `WithCollectors()` mutually exclusive. I'm ok with that until we find a legit use case that needs both

**Comment by varshaprasad96** [comment]
> This will make using `WithCollector()` and `WithCollectors()` mutually exclusive. I'm ok with that until we find a legit use case that needs both

I thought the same. But there may be a case when user wants to selectively publish a certain metric out of the list (for some purpose, I suppose). `WithCollector()` maybe useful for that.
I am not sure though. If it seems to be redundant, I am open to removing it!

**Comment by fahlmant** [comment]
@varshaprasad96 There may be a use case, but I would like to see one first. I think your PR as of now is great. We can fix the mutual exclusivity later if we find we need to. Thanks for this PR!

**Pull request merged**
