### PR TITLE
Bump deps to 4.10 OpenShift release

### PR DESCRIPTION
**Pull request by fahlmant**
Bump dependencies to use 4.10 OpenShift release versions

### CODE REVIEW

**Comment by cblecker** [comment]
LGTM

**Comment by fahlmant** [comment]
/hold
```
../../../../../pkg/mod/sigs.k8s.io/json@v0.0.0-20211020170558-c049b76a60c6/internal/golang/encoding/json/encode.go:1255:18: sf.IsExported undefined (type reflect.StructField has no field or method IsExported)
```
need to fix this

**Comment by 2uasimojo** [comment]
I believe this means you need to build under go 1.17.

**Comment by fahlmant** [comment]
@2uasimojo unfortunately, that gives me
```
 go-1.17 run example/example.go
../../../../pkg/mod/k8s.io/client-go@v0.23.0/plugin/pkg/client/auth/exec/metrics.go:21:2: package io/fs is not in GOROOT (/usr/local/go/src/io/fs)
../../../../pkg/mod/github.com/prometheus/client_golang@v1.12.1/prometheus/internal/go_runtime_metrics.go:22:2: package runtime/metrics is not in GOROOT (/usr/local/go/src/runtime/metrics)
```
I believe this means client-go requires 1.16

https://github.com/kubernetes/client-go/blob/master/go.mod#L5

**Comment by fahlmant** [comment]
Nvm, I just needed to update the Go SDK on my localhost.

**Pull request merged**
