### PR TITLE
Style cleanup and typo fix

### PR DESCRIPTION
**Pull request by yeya24**
Signed-off-by: yeya24 <yb532204897@gmail.com>

Some cleanup and typo fix.

### CODE REVIEW

**Comment by yeya24** [comment]
I tried to support using custom Prometheus registry, but the current design in this package is not flexible enough to achieve this.

**Comment by fahlmant** [comment]
@yeya24 Thank you, I will take a look at this soon.

Could you link to any documentation about registries and why they would be good to support?

**Comment by yeya24** [comment]
@fahlmant Hello, thanks for the reply. 

Prometheus supports two wrap functions here https://github.com/prometheus/client_golang/blob/master/prometheus/wrap.go `WrapRegistererWith(labels Labels, reg Registerer) Registerer` and `WrapRegistererWithPrefix(prefix string, reg Registerer) Registerer`. 

Withe these two functions, we can wrap some common metrics label and metrics name prefix in the registry. 

An example use case is here https://github.com/openshift/aws-account-operator/blob/master/pkg/localmetrics/localmetrics.go, all metrics have a constant label `name=aws-account-operator`.

**Comment by fahlmant** [comment]
Thanks @yeya24. Is there any documentation explaining what the registries are actually doing though? I can see the code is easy to implement.

**Comment by yeya24** [comment]
Registry is just the internal data struct to keep Prometheus metrics in memory. Thanos uses a lot of custom registries https://github.com/thanos-io/thanos/search?q=WrapRegistererWithPrefix&unscoped_q=WrapRegistererWithPrefix. 

It is not difficult to do. If it is okay I can do this in a separate PR, but I think it is not elegant enough because the logic of metrics registering and the `/metrics` endpoint serving is coupled.

Anyway, this is just a nice-to-have feature and it is not very important.
It would be appreciated if you could review this PR first. 😄

**Review by fahlmant — APPROVED** [review]

**Pull request merged**
